services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USDA_API_KEY=${USDA_API_KEY}
      - INSTACART_API_KEY=${INSTACART_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - PYTHONPATH=/app
    networks:
      - mealplan-network
    depends_on:
      - mongodb
    
  payments:
      build:
        context: ./payments
      ports:
        - "4242:4242"
      environment:
        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
        - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
        - AUTH0_DOMAIN=${AUTH0_DOMAIN}
        - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
        - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
        - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      networks:
      - mealplan-network
      
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_AUTH0_DOMAIN: ${NEXT_PUBLIC_AUTH0_DOMAIN}
        NEXT_PUBLIC_AUTH0_AUDIENCE: ${NEXT_PUBLIC_AUTH0_AUDIENCE}    
        NEXT_PUBLIC_PAYMENT_API_URL: ${NEXT_PUBLIC_PAYMENT_API_URL}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_AUTH0_DOMAIN=${NEXT_PUBLIC_AUTH0_DOMAIN}
      - NEXT_PUBLIC_AUTH0_AUDIENCE=${NEXT_PUBLIC_AUTH0_AUDIENCE}
      - NEXT_PUBLIC_PAYMENT_API_URL=${NEXT_PUBLIC_PAYMENT_API_URL}
    networks:
      - mealplan-network
    depends_on:
      - backend
      - payments

  mongodb:
    image: mongo:7.0
    container_name: grovli-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mealplan-network

volumes:
  mongodb_data:

networks:
  mealplan-network: