version: '3.8'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USDA_API_KEY=${USDA_API_KEY}
      - INSTACART_API_KEY=${INSTACART_API_KEY}
      - PYTHONPATH=/app
    networks:
      - mealplan-network
      
  frontend:
    build: ./frontend/mealplan-nextjs
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    networks:
      - mealplan-network
    depends_on:
      - backend

networks:
  mealplan-network: