services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USDA_API_KEY=${USDA_API_KEY}
      - INSTACART_API_KEY=${INSTACART_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - PYTHONPATH=/app
    networks:
      - mealplan-network
    depends_on:
      - mongodb
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    
  payments:
      build:
        context: ./payments
      ports:
        - "4242:4242"
      environment:
        - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
        - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
        - AUTH0_DOMAIN=${AUTH0_DOMAIN}
        - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
        - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
        - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      networks:
      - mealplan-network

  frontend:
    build:
      context: ./frontend
      args:
        # Required Auth0 server-side variables
        AUTH0_DOMAIN: ${AUTH0_DOMAIN}
        AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
        AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
        AUTH0_SECRET: ${AUTH0_SECRET}
        APP_BASE_URL: ${APP_BASE_URL}
        # Other build args
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    environment:
      # Server-side Auth0 variables
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_SECRET=${AUTH0_SECRET}
      - APP_BASE_URL=${APP_BASE_URL}
      # Client-side variables with NEXT_PUBLIC prefix
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - mealplan-network
    depends_on:
      - backend
      - payments
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

  mongodb:
    image: mongo:7.0
    container_name: grovli-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mealplan-network

volumes:
  mongodb_data:

networks:
  mealplan-network: